/// ORIGIN is a well-known mandatory attribute.
/// 
/// The ORIGIN attribute is
/// generated by the speaker that originates the associated routing
/// information.  Its value SHOULD NOT be changed by any other speaker.
#[derive(PartialEq, Debug)]
pub enum Origin {
    /// Network Layer Reachability Information is interior to the originating AS
    Igp,
    /// Network Layer Reachability Information learned via the EGP protocol [RFC904]
    Egp,
    /// Network Layer Reachability Information learned by some other means
    Incomplete,
    Unknown,
}

